Module for reading a pin using G-code command
Smoothieware/Smoothieware pull request #1206
Opened 2017-07-27 10:31 UTC by bullestock

This adds a new `readpin` module which I have found useful for debugging. Sample usage:
```
readpin.d1.enable                            true
readpin.d1.pin                               2.11
readpin.d1.gcode                             M700
```
Now, issuing `M700` prints the current state of pin 2.11 to the console.

2017-07-27 14:53 UTC, wolfmanjm requested changes

2017-07-27 14:53 UTC, wolfmanjm commented on src/main.cpp
> +    auto rpp = new ReadPinPool();
This needs to be protected with `#ifndef NO_UTILS_READPIN` like all the other modules.

2017-07-27 14:55 UTC, wolfmanjm commented on src/modules/utils/readpin/ReadPin.cpp
> +        my_pin.pull_none();
This should not be required it should use the standard pin definitions.

2017-07-27 14:57 UTC, bullestock commented on src/modules/utils/readpin/ReadPin.cpp
> +        my_pin.pull_none();
@wolfmanjm you mean the pull_none() call? I kinda forgot about that, when I first tried the pin apparently had a pull-up.

2017-07-27 14:57 UTC, wolfmanjm requested changes

2017-07-27 14:57 UTC, wolfmanjm commented on src/modules/utils/readpin/ReadPin.cpp
> +    THEKERNEL->slow_ticker->attach(5, this, &ReadPin::pin_tick);
This is an absolute waste of CPU resources, just read the pin on demand not 5 times a second all the time.

2017-07-27 15:01 UTC, bullestock commented on src/modules/utils/readpin/ReadPin.cpp
> +    THEKERNEL->slow_ticker->attach(5, this, &ReadPin::pin_tick);
Yeah, I don't know what I was thinking there...

2017-07-27 15:01 UTC, wolfmanjm commented on src/modules/utils/readpin/ReadPin.cpp
> +        my_pin.pull_none();
Yes, it is pullup by default you would define the pin as P1.2- to disable the pullup.
http://smoothieware.org/configuring-smoothie#advanced-pin-configuration

2017-07-27 16:44 UTC, Zaaphod commented
I have been interested in doing this as well.  I see there is output for 'Pin is not connected'  Is smoothie able to tell if an input is floating?  Or does that mean the pin is not defined?

2017-07-27 16:52 UTC, wolfmanjm commented
TBH this is not needed there is already a  `switch` command, and you can define a switch in config for an input instead, so I see this as a duplication of functionality  that uses up valuable flash space.

2017-07-27 17:00 UTC, Zaaphod commented
I thought the input switch could only be used to turn an output on or off,  can you somehow query the status of the switch to the host with it?

2017-07-27 17:01 UTC, wolfmanjm commented
Yes, you can set a switch to be an input and read it with `switch name`

2017-07-27 17:17 UTC, Zaaphod commented
Awesome that works!  I don't see it documented here http://smoothieware.org/switch unless I'm missing it.  It would be a good thing to add to examples,  I've had occasion to want the host to do something based on the condition of an external input and this would save the extra hardware I've been using.

2017-07-28 11:04 UTC, bullestock commented
Right, if that had been documented I wouldn't have bothered.

2017-07-28 11:04 UTC, closed without merging